name: akhbarak_el_youm
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  intl: ^0.17.0 # Add this line


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.3.0
  provider: ^6.0.4
  lottie: ^2.0.0
  shared_preferences: ^2.0.17
  share_plus: ^6.3.0
  flutter_screenutil: ^5.6.0
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:

  generate: true

  uses-material-design: true
  assets:
    - assets/images/


  